(function() {var implementors = {};
implementors["basic_dsp_matrix"] = [{text:"impl&lt;S:&nbsp;ToSlice&lt;T&gt;, V:&nbsp;Vector&lt;T&gt;, T:&nbsp;RealNumber&gt; SumOps&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/vec/struct.Vec.html\" title=\"struct alloc::vec::Vec\">Vec</a>&lt;T&gt;&gt; for <a class=\"struct\" href=\"basic_dsp_matrix/struct.MatrixMxN.html\" title=\"struct basic_dsp_matrix::MatrixMxN\">MatrixMxN</a>&lt;V, S, T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;V: SumOps&lt;T&gt;,&nbsp;</span>",synthetic:false,types:["basic_dsp_matrix::MatrixMxN"]},{text:"impl&lt;S:&nbsp;ToSlice&lt;T&gt;, V:&nbsp;Vector&lt;T&gt;, T:&nbsp;RealNumber&gt; SumOps&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.array.html\">[</a>T<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.array.html\">; 2]</a>&gt; for <a class=\"struct\" href=\"basic_dsp_matrix/struct.Matrix2xN.html\" title=\"struct basic_dsp_matrix::Matrix2xN\">Matrix2xN</a>&lt;V, S, T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;V: SumOps&lt;T&gt;,&nbsp;</span>",synthetic:false,types:["basic_dsp_matrix::Matrix2xN"]},{text:"impl&lt;S:&nbsp;ToSlice&lt;T&gt;, V:&nbsp;Vector&lt;T&gt;, T:&nbsp;RealNumber&gt; SumOps&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.array.html\">[</a>T<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.array.html\">; 3]</a>&gt; for <a class=\"struct\" href=\"basic_dsp_matrix/struct.Matrix2xN.html\" title=\"struct basic_dsp_matrix::Matrix2xN\">Matrix2xN</a>&lt;V, S, T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;V: SumOps&lt;T&gt;,&nbsp;</span>",synthetic:false,types:["basic_dsp_matrix::Matrix2xN"]},{text:"impl&lt;S:&nbsp;ToSlice&lt;T&gt;, V:&nbsp;Vector&lt;T&gt;, T:&nbsp;RealNumber&gt; SumOps&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.array.html\">[</a>T<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.array.html\">; 4]</a>&gt; for <a class=\"struct\" href=\"basic_dsp_matrix/struct.Matrix2xN.html\" title=\"struct basic_dsp_matrix::Matrix2xN\">Matrix2xN</a>&lt;V, S, T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;V: SumOps&lt;T&gt;,&nbsp;</span>",synthetic:false,types:["basic_dsp_matrix::Matrix2xN"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
