mod elementary;
pub use self::elementary::*;
mod trigonometry_and_powers;
pub use self::trigonometry_and_powers::*;
mod data_reorganization;
pub use self::data_reorganization::*;
mod diff_sum;
pub use self::diff_sum::*;
mod dot_products;
pub use self::dot_products::*;
mod statistics;
pub use self::statistics::*;
